name: gizmogrub_lints_localization
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  carousel_slider: ^5.0.0
  dio: ^5.8.0+1
  get_it: ^8.0.3
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter_bloc: ^9.1.0
  auto_route: ^10.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

  fonts:
    - family: LobsterFamily
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf

    - family: PoppinsFamily
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

    - family: InterFamily
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
